### ISSUE TITLE
error with all the `ee-` commands

### ISSUE THREAD

**Issue by emacsbliss** [eval-exec/eee.el#12]
when I run `M-x eee-rg`, nothing seems happening and I only saw `ee-rg get:` in minibuffer.

Then I tried to run `eee-rg.sh` manually, I got this error:

```
unknown action: become(/Users/emacsbliss/.dotfiles/emacs/straight/repos/eee.el/eee-rg.sh)
```

After further digging, the error seems caused by code below from `eee-common.sh`:

```
FZF_BINDS="\
f1:become(${EEE_RG_SCRIPT}),\
f2:become(${EEE_FIND_SCRIPT} {}),\
f3:execute(${EEE_SYMBOL_SCRIPT} {})\
"
```

I commented this out and also this line from `eee-rg.sh`, things seem working:

```
	--bind "${FZF_BINDS}" \
```

not sure why it's working for me and what's the proper fix would be?

I'm using MacOS (M1, Sonoma 14.3.1), Emacs 29.

**Comment by eval-exec** [comment]
I think eee.el's source code `/Users/emacsbliss/.dotfiles/emacs/straight/repos/eee.el/eee-rg.sh` exist in you device.

Does eee.el's straight builds file: `/Users/emacsbliss/.dotfiles/emacs/straight/builds/eee.el/eee-rg.sh` exist in your device too?

**Comment by emacsbliss** [comment]
yes, the files under `straight/builds` is simply a symlink to the files under `repos`. 

I'm not sure what's that `f1:become` is doing which is causing the issue for me

**Comment by eval-exec** [comment]
Could you share your configuration  code related eee.el?

**Comment by emacsbliss** [comment]
with latest version, things have been working for me
