### ISSUE TITLE
`ee-rga`: error of the type `[Command failed: rga --no-heading 'Emacs' ""]`

### ISSUE THREAD

**Issue by maxecharel** [eval-exec/eee.el#16]
Hi! I am currently testing the package, pretty cool, and thanks for having implemented the call to ripgrep-all. While `ee-rg` and `ee-find` work for me (for `ee-find`, need to first explicitly switch to file 'mode' with `C-f`, but at the end it works), `ee-rga` gives me the following error:
```
[Command failed: rga --no-heading 'Emacs' ""]
```
(note that here I ran the command from a directory where I stored a pdf version of the Emacs manual, and that running the same command without the `""` directly from Wezterm or Konsole works fine)

A priori I would say that the issue is linked to the `""` that is automatically inserted at the end of the command, but I may be missing something.

**Comment by eval-exec** [comment]
Hello, Thanks for your report, I think ee-rga not handle the case when `buffer-file-name` is nil (like in a dired buffer). I fix it in  #17

**Comment by eval-exec** [comment]
@maxecharel I think you may like `yazi` to preview and search pdf files: https://github.com/Urie96/preview.yazi

**Comment by maxecharel** [comment]
> @maxecharel I think you may like `yazi` to preview and search pdf files: https://github.com/Urie96/preview.yazi

Thank you for the suggestion, will try it.

**Comment by maxecharel** [comment]
> Hello, Thanks for your report, I think ee-rga not handle the case when `buffer-file-name` is nil (like in a dired buffer). I fix it in #17

Thanks for the quick fix! Tested it, now works like a charm when called from Dired. BTW, if you're willing to, would be nice to enable `Discussions` to discuss interesting new features without bloating `Issues`. Thank you for the great work!

**Comment by eval-exec** [comment]
Thanks for your test, I enabled discussions now. :blue_heart: 

https://github.com/eval-exec/eee.el/discussions
